name: CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run Tests
        run: |
          go test -v ./...

      - name: Build Application
        run: |
          go build -v ./cmd/main.go
